type: yml
DB:
  mysql: mysql
  user: root
  password: 12345
  host: localhost
  port:  3309
  name:  gameapp

auth:
  token_access_duration: "720h0m0s"
  token_refresh_duration: "720h0m0s"
#  token_secret_key: "ddddddddddddddddddddd"


redis:
  host: localhost
  port: 6379
  password: ""
  db: 0


presence:
  key_prefix: "presenceadapter"
  presence_expire_duration: "60m"